# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.istio_authorization_policy import IstioAuthorizationPolicy  # noqa: E501
from openapi_client.rest import ApiException

class TestIstioAuthorizationPolicy(unittest.TestCase):
    """IstioAuthorizationPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IstioAuthorizationPolicy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.istio_authorization_policy.IstioAuthorizationPolicy()  # noqa: E501
        if include_optional :
            return IstioAuthorizationPolicy(
                effect = '[\"allow\",\"alert\",\"prevent\",\"monitor\",\"\"]', 
                name = '', 
                namespace = '', 
                rules = [
                    openapi_client.models.istio/authorization_policy_rule.istio.AuthorizationPolicyRule(
                        destinations = [
                            openapi_client.models.istio/authorization_policy_destination.istio.AuthorizationPolicyDestination(
                                methods = [
                                    ''
                                    ], 
                                paths = [
                                    ''
                                    ], 
                                ports = [
                                    56
                                    ], )
                            ], 
                        sources = [
                            openapi_client.models.istio/authorization_policy_source.istio.AuthorizationPolicySource(
                                namespaces = [
                                    ''
                                    ], 
                                principals = [
                                    ''
                                    ], )
                            ], )
                    ], 
                target_services = [
                    openapi_client.models.istio/authorization_policy_service.istio.AuthorizationPolicyService(
                        name = '', 
                        namespace = '', )
                    ]
            )
        else :
            return IstioAuthorizationPolicy(
        )

    def testIstioAuthorizationPolicy(self):
        """Test IstioAuthorizationPolicy"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
