# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.waas_unknown_bot_protection_spec import WaasUnknownBotProtectionSpec  # noqa: E501
from openapi_client.rest import ApiException

class TestWaasUnknownBotProtectionSpec(unittest.TestCase):
    """WaasUnknownBotProtectionSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WaasUnknownBotProtectionSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.waas_unknown_bot_protection_spec.WaasUnknownBotProtectionSpec()  # noqa: E501
        if include_optional :
            return WaasUnknownBotProtectionSpec(
                api_libraries = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]', 
                bot_impersonation = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]', 
                browser_impersonation = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]', 
                generic = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]', 
                http_libraries = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]', 
                request_anomalies = ERROR_TO_EXAMPLE_VALUE, 
                web_automation_tools = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]', 
                web_scrapers = '[\"ban\",\"prevent\",\"alert\",\"allow\",\"disable\",\"reCAPTCHA\"]'
            )
        else :
            return WaasUnknownBotProtectionSpec(
        )

    def testWaasUnknownBotProtectionSpec(self):
        """Test WaasUnknownBotProtectionSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
