# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.shared_scan_settings import SharedScanSettings  # noqa: E501
from openapi_client.rest import ApiException

class TestSharedScanSettings(unittest.TestCase):
    """SharedScanSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SharedScanSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.shared_scan_settings.SharedScanSettings()  # noqa: E501
        if include_optional :
            return SharedScanSettings(
                cloud_platforms_scan_period_ms = 56, 
                code_repos_scan_period_ms = 56, 
                containers_scan_period_ms = 56, 
                extract_archive = True, 
                images_scan_period_ms = 56, 
                include_js_dependencies = True, 
                registry_scan_period_ms = 56, 
                registry_scan_retention_days = 56, 
                scan_running_images = True, 
                serverless_scan_period_ms = 56, 
                show_infra_containers = True, 
                show_negligible_vulnerabilities = True, 
                system_scan_period_ms = 56, 
                tas_droplets_scan_period_ms = 56, 
                vm_scan_period_ms = 56
            )
        else :
            return SharedScanSettings(
        )

    def testSharedScanSettings(self):
        """Test SharedScanSettings"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
