# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.trust_data import TrustData  # noqa: E501
from openapi_client.rest import ApiException

class TestTrustData(unittest.TestCase):
    """TrustData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TrustData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.trust_data.TrustData()  # noqa: E501
        if include_optional :
            return TrustData(
                groups = [
                    openapi_client.models.trust/group.trust.Group(
                        _id = '', 
                        disabled = True, 
                        images = [
                            ''
                            ], 
                        layers = [
                            ''
                            ], 
                        modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        notes = '', 
                        owner = '', 
                        previous_name = '', )
                    ], 
                policy = openapi_client.models.trust/policy.trust.Policy(
                    _id = '', 
                    enabled = True, 
                    rules = [
                        openapi_client.models.trust/policy_rule.trust.PolicyRule(
                            allowed_groups = [
                                ''
                                ], 
                            block_msg = '', 
                            collections = [
                                openapi_client.models.collection/collection.collection.Collection(
                                    account_ids = [
                                        ''
                                        ], 
                                    app_ids = [
                                        ''
                                        ], 
                                    clusters = [
                                        ''
                                        ], 
                                    code_repos = [
                                        ''
                                        ], 
                                    color = '', 
                                    containers = [
                                        ''
                                        ], 
                                    description = '', 
                                    functions = [
                                        ''
                                        ], 
                                    hosts = [
                                        ''
                                        ], 
                                    images = [
                                        ''
                                        ], 
                                    labels = [
                                        ''
                                        ], 
                                    modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    name = '', 
                                    namespaces = [
                                        ''
                                        ], 
                                    owner = '', 
                                    prisma = True, 
                                    system = True, )
                                ], 
                            denied_groups = [
                                ''
                                ], 
                            disabled = True, 
                            effect = '[\"ignore\",\"alert\",\"block\"]', 
                            modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            name = '', 
                            notes = '', 
                            owner = '', 
                            previous_name = '', )
                        ], )
            )
        else :
            return TrustData(
        )

    def testTrustData(self):
        """Test TrustData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
