# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class CnnfRadarPolicyRule(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'effect': 'CommonEffect',
        'port_ranges': 'list[CommonPortRange]'
    }

    attribute_map = {
        'effect': 'effect',
        'port_ranges': 'portRanges'
    }

    def __init__(self, effect=None, port_ranges=None, local_vars_configuration=None):  # noqa: E501
        """CnnfRadarPolicyRule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._effect = None
        self._port_ranges = None
        self.discriminator = None

        if effect is not None:
            self.effect = effect
        if port_ranges is not None:
            self.port_ranges = port_ranges

    @property
    def effect(self):
        """Gets the effect of this CnnfRadarPolicyRule.  # noqa: E501


        :return: The effect of this CnnfRadarPolicyRule.  # noqa: E501
        :rtype: CommonEffect
        """
        return self._effect

    @effect.setter
    def effect(self, effect):
        """Sets the effect of this CnnfRadarPolicyRule.


        :param effect: The effect of this CnnfRadarPolicyRule.  # noqa: E501
        :type effect: CommonEffect
        """

        self._effect = effect

    @property
    def port_ranges(self):
        """Gets the port_ranges of this CnnfRadarPolicyRule.  # noqa: E501

        PortRanges specify the ranges of ports.   # noqa: E501

        :return: The port_ranges of this CnnfRadarPolicyRule.  # noqa: E501
        :rtype: list[CommonPortRange]
        """
        return self._port_ranges

    @port_ranges.setter
    def port_ranges(self, port_ranges):
        """Sets the port_ranges of this CnnfRadarPolicyRule.

        PortRanges specify the ranges of ports.   # noqa: E501

        :param port_ranges: The port_ranges of this CnnfRadarPolicyRule.  # noqa: E501
        :type port_ranges: list[CommonPortRange]
        """

        self._port_ranges = port_ranges

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CnnfRadarPolicyRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CnnfRadarPolicyRule):
            return True

        return self.to_dict() != other.to_dict()
