# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class CommonRuntimeResource(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'account_ids': 'list[str]',
        'app_ids': 'list[str]',
        'clusters': 'list[str]',
        'code_repos': 'list[str]',
        'containers': 'list[str]',
        'functions': 'list[str]',
        'hosts': 'list[str]',
        'images': 'list[str]',
        'labels': 'list[str]',
        'namespaces': 'list[str]'
    }

    attribute_map = {
        'account_ids': 'accountIDs',
        'app_ids': 'appIDs',
        'clusters': 'clusters',
        'code_repos': 'codeRepos',
        'containers': 'containers',
        'functions': 'functions',
        'hosts': 'hosts',
        'images': 'images',
        'labels': 'labels',
        'namespaces': 'namespaces'
    }

    def __init__(self, account_ids=None, app_ids=None, clusters=None, code_repos=None, containers=None, functions=None, hosts=None, images=None, labels=None, namespaces=None, local_vars_configuration=None):  # noqa: E501
        """CommonRuntimeResource - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._account_ids = None
        self._app_ids = None
        self._clusters = None
        self._code_repos = None
        self._containers = None
        self._functions = None
        self._hosts = None
        self._images = None
        self._labels = None
        self._namespaces = None
        self.discriminator = None

        if account_ids is not None:
            self.account_ids = account_ids
        if app_ids is not None:
            self.app_ids = app_ids
        if clusters is not None:
            self.clusters = clusters
        if code_repos is not None:
            self.code_repos = code_repos
        if containers is not None:
            self.containers = containers
        if functions is not None:
            self.functions = functions
        if hosts is not None:
            self.hosts = hosts
        if images is not None:
            self.images = images
        if labels is not None:
            self.labels = labels
        if namespaces is not None:
            self.namespaces = namespaces

    @property
    def account_ids(self):
        """Gets the account_ids of this CommonRuntimeResource.  # noqa: E501

        List of account IDs.   # noqa: E501

        :return: The account_ids of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._account_ids

    @account_ids.setter
    def account_ids(self, account_ids):
        """Sets the account_ids of this CommonRuntimeResource.

        List of account IDs.   # noqa: E501

        :param account_ids: The account_ids of this CommonRuntimeResource.  # noqa: E501
        :type account_ids: list[str]
        """

        self._account_ids = account_ids

    @property
    def app_ids(self):
        """Gets the app_ids of this CommonRuntimeResource.  # noqa: E501

        List of application IDs.   # noqa: E501

        :return: The app_ids of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._app_ids

    @app_ids.setter
    def app_ids(self, app_ids):
        """Sets the app_ids of this CommonRuntimeResource.

        List of application IDs.   # noqa: E501

        :param app_ids: The app_ids of this CommonRuntimeResource.  # noqa: E501
        :type app_ids: list[str]
        """

        self._app_ids = app_ids

    @property
    def clusters(self):
        """Gets the clusters of this CommonRuntimeResource.  # noqa: E501

        List of Kubernetes cluster names.   # noqa: E501

        :return: The clusters of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._clusters

    @clusters.setter
    def clusters(self, clusters):
        """Sets the clusters of this CommonRuntimeResource.

        List of Kubernetes cluster names.   # noqa: E501

        :param clusters: The clusters of this CommonRuntimeResource.  # noqa: E501
        :type clusters: list[str]
        """

        self._clusters = clusters

    @property
    def code_repos(self):
        """Gets the code_repos of this CommonRuntimeResource.  # noqa: E501

        List of code repositories.   # noqa: E501

        :return: The code_repos of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._code_repos

    @code_repos.setter
    def code_repos(self, code_repos):
        """Sets the code_repos of this CommonRuntimeResource.

        List of code repositories.   # noqa: E501

        :param code_repos: The code_repos of this CommonRuntimeResource.  # noqa: E501
        :type code_repos: list[str]
        """

        self._code_repos = code_repos

    @property
    def containers(self):
        """Gets the containers of this CommonRuntimeResource.  # noqa: E501

        List of containers.   # noqa: E501

        :return: The containers of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._containers

    @containers.setter
    def containers(self, containers):
        """Sets the containers of this CommonRuntimeResource.

        List of containers.   # noqa: E501

        :param containers: The containers of this CommonRuntimeResource.  # noqa: E501
        :type containers: list[str]
        """

        self._containers = containers

    @property
    def functions(self):
        """Gets the functions of this CommonRuntimeResource.  # noqa: E501

        List of functions.   # noqa: E501

        :return: The functions of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._functions

    @functions.setter
    def functions(self, functions):
        """Sets the functions of this CommonRuntimeResource.

        List of functions.   # noqa: E501

        :param functions: The functions of this CommonRuntimeResource.  # noqa: E501
        :type functions: list[str]
        """

        self._functions = functions

    @property
    def hosts(self):
        """Gets the hosts of this CommonRuntimeResource.  # noqa: E501

        List of  hosts.   # noqa: E501

        :return: The hosts of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this CommonRuntimeResource.

        List of  hosts.   # noqa: E501

        :param hosts: The hosts of this CommonRuntimeResource.  # noqa: E501
        :type hosts: list[str]
        """

        self._hosts = hosts

    @property
    def images(self):
        """Gets the images of this CommonRuntimeResource.  # noqa: E501

        List of images.   # noqa: E501

        :return: The images of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this CommonRuntimeResource.

        List of images.   # noqa: E501

        :param images: The images of this CommonRuntimeResource.  # noqa: E501
        :type images: list[str]
        """

        self._images = images

    @property
    def labels(self):
        """Gets the labels of this CommonRuntimeResource.  # noqa: E501

        List of labels.   # noqa: E501

        :return: The labels of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this CommonRuntimeResource.

        List of labels.   # noqa: E501

        :param labels: The labels of this CommonRuntimeResource.  # noqa: E501
        :type labels: list[str]
        """

        self._labels = labels

    @property
    def namespaces(self):
        """Gets the namespaces of this CommonRuntimeResource.  # noqa: E501

        List of Kubernetes namespaces.   # noqa: E501

        :return: The namespaces of this CommonRuntimeResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._namespaces

    @namespaces.setter
    def namespaces(self, namespaces):
        """Sets the namespaces of this CommonRuntimeResource.

        List of Kubernetes namespaces.   # noqa: E501

        :param namespaces: The namespaces of this CommonRuntimeResource.  # noqa: E501
        :type namespaces: list[str]
        """

        self._namespaces = namespaces

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommonRuntimeResource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CommonRuntimeResource):
            return True

        return self.to_dict() != other.to_dict()
