# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class RuntimeHostNetworkRule(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'allowed_outbound_ips': 'list[str]',
        'custom_feed': 'RuntimeRuleEffect',
        'denied_listening_ports': 'list[CommonPortRange]',
        'denied_outbound_ips': 'list[str]',
        'denied_outbound_ports': 'list[CommonPortRange]',
        'deny_list_effect': 'RuntimeRuleEffect',
        'intelligence_feed': 'RuntimeRuleEffect'
    }

    attribute_map = {
        'allowed_outbound_ips': 'allowedOutboundIPs',
        'custom_feed': 'customFeed',
        'denied_listening_ports': 'deniedListeningPorts',
        'denied_outbound_ips': 'deniedOutboundIPs',
        'denied_outbound_ports': 'deniedOutboundPorts',
        'deny_list_effect': 'denyListEffect',
        'intelligence_feed': 'intelligenceFeed'
    }

    def __init__(self, allowed_outbound_ips=None, custom_feed=None, denied_listening_ports=None, denied_outbound_ips=None, denied_outbound_ports=None, deny_list_effect=None, intelligence_feed=None, local_vars_configuration=None):  # noqa: E501
        """RuntimeHostNetworkRule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._allowed_outbound_ips = None
        self._custom_feed = None
        self._denied_listening_ports = None
        self._denied_outbound_ips = None
        self._denied_outbound_ports = None
        self._deny_list_effect = None
        self._intelligence_feed = None
        self.discriminator = None

        if allowed_outbound_ips is not None:
            self.allowed_outbound_ips = allowed_outbound_ips
        if custom_feed is not None:
            self.custom_feed = custom_feed
        if denied_listening_ports is not None:
            self.denied_listening_ports = denied_listening_ports
        if denied_outbound_ips is not None:
            self.denied_outbound_ips = denied_outbound_ips
        if denied_outbound_ports is not None:
            self.denied_outbound_ports = denied_outbound_ports
        if deny_list_effect is not None:
            self.deny_list_effect = deny_list_effect
        if intelligence_feed is not None:
            self.intelligence_feed = intelligence_feed

    @property
    def allowed_outbound_ips(self):
        """Gets the allowed_outbound_ips of this RuntimeHostNetworkRule.  # noqa: E501

        AllowedOutboundIPs is a list of IPs to skip checks for.   # noqa: E501

        :return: The allowed_outbound_ips of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: list[str]
        """
        return self._allowed_outbound_ips

    @allowed_outbound_ips.setter
    def allowed_outbound_ips(self, allowed_outbound_ips):
        """Sets the allowed_outbound_ips of this RuntimeHostNetworkRule.

        AllowedOutboundIPs is a list of IPs to skip checks for.   # noqa: E501

        :param allowed_outbound_ips: The allowed_outbound_ips of this RuntimeHostNetworkRule.  # noqa: E501
        :type allowed_outbound_ips: list[str]
        """

        self._allowed_outbound_ips = allowed_outbound_ips

    @property
    def custom_feed(self):
        """Gets the custom_feed of this RuntimeHostNetworkRule.  # noqa: E501


        :return: The custom_feed of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: RuntimeRuleEffect
        """
        return self._custom_feed

    @custom_feed.setter
    def custom_feed(self, custom_feed):
        """Sets the custom_feed of this RuntimeHostNetworkRule.


        :param custom_feed: The custom_feed of this RuntimeHostNetworkRule.  # noqa: E501
        :type custom_feed: RuntimeRuleEffect
        """

        self._custom_feed = custom_feed

    @property
    def denied_listening_ports(self):
        """Gets the denied_listening_ports of this RuntimeHostNetworkRule.  # noqa: E501

        DeniedListeningPorts is a list of listening ports to deny.   # noqa: E501

        :return: The denied_listening_ports of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: list[CommonPortRange]
        """
        return self._denied_listening_ports

    @denied_listening_ports.setter
    def denied_listening_ports(self, denied_listening_ports):
        """Sets the denied_listening_ports of this RuntimeHostNetworkRule.

        DeniedListeningPorts is a list of listening ports to deny.   # noqa: E501

        :param denied_listening_ports: The denied_listening_ports of this RuntimeHostNetworkRule.  # noqa: E501
        :type denied_listening_ports: list[CommonPortRange]
        """

        self._denied_listening_ports = denied_listening_ports

    @property
    def denied_outbound_ips(self):
        """Gets the denied_outbound_ips of this RuntimeHostNetworkRule.  # noqa: E501

        DeniedOutboundIPs is a list of outbound IPs to deny.   # noqa: E501

        :return: The denied_outbound_ips of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: list[str]
        """
        return self._denied_outbound_ips

    @denied_outbound_ips.setter
    def denied_outbound_ips(self, denied_outbound_ips):
        """Sets the denied_outbound_ips of this RuntimeHostNetworkRule.

        DeniedOutboundIPs is a list of outbound IPs to deny.   # noqa: E501

        :param denied_outbound_ips: The denied_outbound_ips of this RuntimeHostNetworkRule.  # noqa: E501
        :type denied_outbound_ips: list[str]
        """

        self._denied_outbound_ips = denied_outbound_ips

    @property
    def denied_outbound_ports(self):
        """Gets the denied_outbound_ports of this RuntimeHostNetworkRule.  # noqa: E501

        DeniedOutboundPorts is a list of outbound ports to deny.   # noqa: E501

        :return: The denied_outbound_ports of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: list[CommonPortRange]
        """
        return self._denied_outbound_ports

    @denied_outbound_ports.setter
    def denied_outbound_ports(self, denied_outbound_ports):
        """Sets the denied_outbound_ports of this RuntimeHostNetworkRule.

        DeniedOutboundPorts is a list of outbound ports to deny.   # noqa: E501

        :param denied_outbound_ports: The denied_outbound_ports of this RuntimeHostNetworkRule.  # noqa: E501
        :type denied_outbound_ports: list[CommonPortRange]
        """

        self._denied_outbound_ports = denied_outbound_ports

    @property
    def deny_list_effect(self):
        """Gets the deny_list_effect of this RuntimeHostNetworkRule.  # noqa: E501


        :return: The deny_list_effect of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: RuntimeRuleEffect
        """
        return self._deny_list_effect

    @deny_list_effect.setter
    def deny_list_effect(self, deny_list_effect):
        """Sets the deny_list_effect of this RuntimeHostNetworkRule.


        :param deny_list_effect: The deny_list_effect of this RuntimeHostNetworkRule.  # noqa: E501
        :type deny_list_effect: RuntimeRuleEffect
        """

        self._deny_list_effect = deny_list_effect

    @property
    def intelligence_feed(self):
        """Gets the intelligence_feed of this RuntimeHostNetworkRule.  # noqa: E501


        :return: The intelligence_feed of this RuntimeHostNetworkRule.  # noqa: E501
        :rtype: RuntimeRuleEffect
        """
        return self._intelligence_feed

    @intelligence_feed.setter
    def intelligence_feed(self, intelligence_feed):
        """Sets the intelligence_feed of this RuntimeHostNetworkRule.


        :param intelligence_feed: The intelligence_feed of this RuntimeHostNetworkRule.  # noqa: E501
        :type intelligence_feed: RuntimeRuleEffect
        """

        self._intelligence_feed = intelligence_feed

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuntimeHostNetworkRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RuntimeHostNetworkRule):
            return True

        return self.to_dict() != other.to_dict()
