# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class SharedContainerRadarIncomingConnection(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'policy_rules': 'list[CnnfRadarPolicyRule]',
        'ports': 'list[CommonPortData]',
        'profile_hash': 'int',
        'profile_id': 'str'
    }

    attribute_map = {
        'policy_rules': 'policyRules',
        'ports': 'ports',
        'profile_hash': 'profileHash',
        'profile_id': 'profileID'
    }

    def __init__(self, policy_rules=None, ports=None, profile_hash=None, profile_id=None, local_vars_configuration=None):  # noqa: E501
        """SharedContainerRadarIncomingConnection - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._policy_rules = None
        self._ports = None
        self._profile_hash = None
        self._profile_id = None
        self.discriminator = None

        if policy_rules is not None:
            self.policy_rules = policy_rules
        if ports is not None:
            self.ports = ports
        if profile_hash is not None:
            self.profile_hash = profile_hash
        if profile_id is not None:
            self.profile_id = profile_id

    @property
    def policy_rules(self):
        """Gets the policy_rules of this SharedContainerRadarIncomingConnection.  # noqa: E501

        PolicyRules are the policy rules that are applicable for source/dest. Used for radar display of connections deduced from policy rules.   # noqa: E501

        :return: The policy_rules of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :rtype: list[CnnfRadarPolicyRule]
        """
        return self._policy_rules

    @policy_rules.setter
    def policy_rules(self, policy_rules):
        """Sets the policy_rules of this SharedContainerRadarIncomingConnection.

        PolicyRules are the policy rules that are applicable for source/dest. Used for radar display of connections deduced from policy rules.   # noqa: E501

        :param policy_rules: The policy_rules of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :type policy_rules: list[CnnfRadarPolicyRule]
        """

        self._policy_rules = policy_rules

    @property
    def ports(self):
        """Gets the ports of this SharedContainerRadarIncomingConnection.  # noqa: E501

        Ports are all the ports used by the sender.   # noqa: E501

        :return: The ports of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :rtype: list[CommonPortData]
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this SharedContainerRadarIncomingConnection.

        Ports are all the ports used by the sender.   # noqa: E501

        :param ports: The ports of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :type ports: list[CommonPortData]
        """

        self._ports = ports

    @property
    def profile_hash(self):
        """Gets the profile_hash of this SharedContainerRadarIncomingConnection.  # noqa: E501

        ProfileHash represents the profile hash It is allowed to contain up to uint32 numbers, and represented by int64 since mongodb does not support unsigned data types  # noqa: E501

        :return: The profile_hash of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :rtype: int
        """
        return self._profile_hash

    @profile_hash.setter
    def profile_hash(self, profile_hash):
        """Sets the profile_hash of this SharedContainerRadarIncomingConnection.

        ProfileHash represents the profile hash It is allowed to contain up to uint32 numbers, and represented by int64 since mongodb does not support unsigned data types  # noqa: E501

        :param profile_hash: The profile_hash of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :type profile_hash: int
        """

        self._profile_hash = profile_hash

    @property
    def profile_id(self):
        """Gets the profile_id of this SharedContainerRadarIncomingConnection.  # noqa: E501

        ProfileID is the sender's profile ID.   # noqa: E501

        :return: The profile_id of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :rtype: str
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id):
        """Sets the profile_id of this SharedContainerRadarIncomingConnection.

        ProfileID is the sender's profile ID.   # noqa: E501

        :param profile_id: The profile_id of this SharedContainerRadarIncomingConnection.  # noqa: E501
        :type profile_id: str
        """

        self._profile_id = profile_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SharedContainerRadarIncomingConnection):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SharedContainerRadarIncomingConnection):
            return True

        return self.to_dict() != other.to_dict()
