# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class TypesTrends(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'compliance_trend': 'list[TypesComplianceDailyStats]',
        'defenders_summary': 'dict(str, int)',
        'vulnerability_summary': 'TypesVulnerabilitySummary'
    }

    attribute_map = {
        'compliance_trend': 'complianceTrend',
        'defenders_summary': 'defendersSummary',
        'vulnerability_summary': 'vulnerabilitySummary'
    }

    def __init__(self, compliance_trend=None, defenders_summary=None, vulnerability_summary=None, local_vars_configuration=None):  # noqa: E501
        """TypesTrends - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._compliance_trend = None
        self._defenders_summary = None
        self._vulnerability_summary = None
        self.discriminator = None

        if compliance_trend is not None:
            self.compliance_trend = compliance_trend
        if defenders_summary is not None:
            self.defenders_summary = defenders_summary
        if vulnerability_summary is not None:
            self.vulnerability_summary = vulnerability_summary

    @property
    def compliance_trend(self):
        """Gets the compliance_trend of this TypesTrends.  # noqa: E501

        ComplianceTrend represents the compliance trend.   # noqa: E501

        :return: The compliance_trend of this TypesTrends.  # noqa: E501
        :rtype: list[TypesComplianceDailyStats]
        """
        return self._compliance_trend

    @compliance_trend.setter
    def compliance_trend(self, compliance_trend):
        """Sets the compliance_trend of this TypesTrends.

        ComplianceTrend represents the compliance trend.   # noqa: E501

        :param compliance_trend: The compliance_trend of this TypesTrends.  # noqa: E501
        :type compliance_trend: list[TypesComplianceDailyStats]
        """

        self._compliance_trend = compliance_trend

    @property
    def defenders_summary(self):
        """Gets the defenders_summary of this TypesTrends.  # noqa: E501

        DefendersSummary represents the defenders count of each category.   # noqa: E501

        :return: The defenders_summary of this TypesTrends.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._defenders_summary

    @defenders_summary.setter
    def defenders_summary(self, defenders_summary):
        """Sets the defenders_summary of this TypesTrends.

        DefendersSummary represents the defenders count of each category.   # noqa: E501

        :param defenders_summary: The defenders_summary of this TypesTrends.  # noqa: E501
        :type defenders_summary: dict(str, int)
        """

        self._defenders_summary = defenders_summary

    @property
    def vulnerability_summary(self):
        """Gets the vulnerability_summary of this TypesTrends.  # noqa: E501


        :return: The vulnerability_summary of this TypesTrends.  # noqa: E501
        :rtype: TypesVulnerabilitySummary
        """
        return self._vulnerability_summary

    @vulnerability_summary.setter
    def vulnerability_summary(self, vulnerability_summary):
        """Sets the vulnerability_summary of this TypesTrends.


        :param vulnerability_summary: The vulnerability_summary of this TypesTrends.  # noqa: E501
        :type vulnerability_summary: TypesVulnerabilitySummary
        """

        self._vulnerability_summary = vulnerability_summary

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TypesTrends):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TypesTrends):
            return True

        return self.to_dict() != other.to_dict()
