# coding: utf-8

"""
    Prisma Cloud Compute API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 21.04.439
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class ServerlessApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_v1_serverless_download_get(self, **kwargs):  # noqa: E501
        """api_v1_serverless_download_get  # noqa: E501

        DownloadServerlessFunctions downloads the serverless functions data to CSVs   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_download_get(async_req=True)
        >>> result = thread.get()

        :param offset: Offset from the start of the list from which to retrieve documents. 
        :type offset: int
        :param limit: Number of documents to return. 
        :type limit: int
        :param search: Search term. 
        :type search: str
        :param sort: Key on which to sort. 
        :type sort: str
        :param reverse: Sort order. 
        :type reverse: bool
        :param collections: Scopes the query by collection. 
        :type collections: list[str]
        :param account_ids: Scopes the query by account ID. 
        :type account_ids: list[str]
        :param fields: List of fields to retrieve. 
        :type fields: list[str]
        :param id: List of function IDs. 
        :type id: list[str]
        :param cloud_controller_addresses: List of cloud controller addresses which hold the functions. 
        :type cloud_controller_addresses: list[str]
        :param provider: Filters results by provider. 
        :type provider: list[str]
        :param region: Filters results by region. 
        :type region: list[str]
        :param runtime: Filters results by runtime. 
        :type runtime: list[str]
        :param version: Filters results by function version. 
        :type version: list[str]
        :param function_layers: Filters results by function layers. 
        :type function_layers: list[str]
        :param defended: Filters results by functions which are defended by a Defender and are connected to Console (true) or not (false). 
        :type defended: bool
        :param compliance_ids: Filters results by compliance ID. 
        :type compliance_ids: list[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_download_get_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_download_get_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_download_get  # noqa: E501

        DownloadServerlessFunctions downloads the serverless functions data to CSVs   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_download_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param offset: Offset from the start of the list from which to retrieve documents. 
        :type offset: int
        :param limit: Number of documents to return. 
        :type limit: int
        :param search: Search term. 
        :type search: str
        :param sort: Key on which to sort. 
        :type sort: str
        :param reverse: Sort order. 
        :type reverse: bool
        :param collections: Scopes the query by collection. 
        :type collections: list[str]
        :param account_ids: Scopes the query by account ID. 
        :type account_ids: list[str]
        :param fields: List of fields to retrieve. 
        :type fields: list[str]
        :param id: List of function IDs. 
        :type id: list[str]
        :param cloud_controller_addresses: List of cloud controller addresses which hold the functions. 
        :type cloud_controller_addresses: list[str]
        :param provider: Filters results by provider. 
        :type provider: list[str]
        :param region: Filters results by region. 
        :type region: list[str]
        :param runtime: Filters results by runtime. 
        :type runtime: list[str]
        :param version: Filters results by function version. 
        :type version: list[str]
        :param function_layers: Filters results by function layers. 
        :type function_layers: list[str]
        :param defended: Filters results by functions which are defended by a Defender and are connected to Console (true) or not (false). 
        :type defended: bool
        :param compliance_ids: Filters results by compliance ID. 
        :type compliance_ids: list[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        local_var_params = locals()

        all_params = [
            'offset',
            'limit',
            'search',
            'sort',
            'reverse',
            'collections',
            'account_ids',
            'fields',
            'id',
            'cloud_controller_addresses',
            'provider',
            'region',
            'runtime',
            'version',
            'function_layers',
            'defended',
            'compliance_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_download_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in local_var_params and local_var_params['offset'] is not None:  # noqa: E501
            query_params.append(('offset', local_var_params['offset']))  # noqa: E501
        if 'limit' in local_var_params and local_var_params['limit'] is not None:  # noqa: E501
            query_params.append(('limit', local_var_params['limit']))  # noqa: E501
        if 'search' in local_var_params and local_var_params['search'] is not None:  # noqa: E501
            query_params.append(('search', local_var_params['search']))  # noqa: E501
        if 'sort' in local_var_params and local_var_params['sort'] is not None:  # noqa: E501
            query_params.append(('sort', local_var_params['sort']))  # noqa: E501
        if 'reverse' in local_var_params and local_var_params['reverse'] is not None:  # noqa: E501
            query_params.append(('reverse', local_var_params['reverse']))  # noqa: E501
        if 'collections' in local_var_params and local_var_params['collections'] is not None:  # noqa: E501
            query_params.append(('collections', local_var_params['collections']))  # noqa: E501
            collection_formats['collections'] = 'multi'  # noqa: E501
        if 'account_ids' in local_var_params and local_var_params['account_ids'] is not None:  # noqa: E501
            query_params.append(('accountIDs', local_var_params['account_ids']))  # noqa: E501
            collection_formats['accountIDs'] = 'multi'  # noqa: E501
        if 'fields' in local_var_params and local_var_params['fields'] is not None:  # noqa: E501
            query_params.append(('fields', local_var_params['fields']))  # noqa: E501
            collection_formats['fields'] = 'multi'  # noqa: E501
        if 'id' in local_var_params and local_var_params['id'] is not None:  # noqa: E501
            query_params.append(('id', local_var_params['id']))  # noqa: E501
            collection_formats['id'] = 'multi'  # noqa: E501
        if 'cloud_controller_addresses' in local_var_params and local_var_params['cloud_controller_addresses'] is not None:  # noqa: E501
            query_params.append(('cloudControllerAddresses', local_var_params['cloud_controller_addresses']))  # noqa: E501
            collection_formats['cloudControllerAddresses'] = 'multi'  # noqa: E501
        if 'provider' in local_var_params and local_var_params['provider'] is not None:  # noqa: E501
            query_params.append(('provider', local_var_params['provider']))  # noqa: E501
            collection_formats['provider'] = 'multi'  # noqa: E501
        if 'region' in local_var_params and local_var_params['region'] is not None:  # noqa: E501
            query_params.append(('region', local_var_params['region']))  # noqa: E501
            collection_formats['region'] = 'multi'  # noqa: E501
        if 'runtime' in local_var_params and local_var_params['runtime'] is not None:  # noqa: E501
            query_params.append(('runtime', local_var_params['runtime']))  # noqa: E501
            collection_formats['runtime'] = 'multi'  # noqa: E501
        if 'version' in local_var_params and local_var_params['version'] is not None:  # noqa: E501
            query_params.append(('version', local_var_params['version']))  # noqa: E501
            collection_formats['version'] = 'multi'  # noqa: E501
        if 'function_layers' in local_var_params and local_var_params['function_layers'] is not None:  # noqa: E501
            query_params.append(('functionLayers', local_var_params['function_layers']))  # noqa: E501
            collection_formats['functionLayers'] = 'multi'  # noqa: E501
        if 'defended' in local_var_params and local_var_params['defended'] is not None:  # noqa: E501
            query_params.append(('defended', local_var_params['defended']))  # noqa: E501
        if 'compliance_ids' in local_var_params and local_var_params['compliance_ids'] is not None:  # noqa: E501
            query_params.append(('complianceIDs', local_var_params['compliance_ids']))  # noqa: E501
            collection_formats['complianceIDs'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {}

        return self.api_client.call_api(
            '/api/v1/serverless/download', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def api_v1_serverless_evaluate_post(self, **kwargs):  # noqa: E501
        """api_v1_serverless_evaluate_post  # noqa: E501

        ResolveFunctions adds vulnerability data for the given functions   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_evaluate_post(async_req=True)
        >>> result = thread.get()

        :param api_resolve_functions_req:
        :type api_resolve_functions_req: ApiResolveFunctionsReq
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ApiResolveFunctionsResp
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_evaluate_post_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_evaluate_post_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_evaluate_post  # noqa: E501

        ResolveFunctions adds vulnerability data for the given functions   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_evaluate_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param api_resolve_functions_req:
        :type api_resolve_functions_req: ApiResolveFunctionsReq
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ApiResolveFunctionsResp, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'api_resolve_functions_req'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_evaluate_post" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'api_resolve_functions_req' in local_var_params:
            body_params = local_var_params['api_resolve_functions_req']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {
            200: "ApiResolveFunctionsResp",
        }

        return self.api_client.call_api(
            '/api/v1/serverless/evaluate', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def api_v1_serverless_get(self, **kwargs):  # noqa: E501
        """api_v1_serverless_get  # noqa: E501

        ServerlessFunctions returns serverless functions   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_get(async_req=True)
        >>> result = thread.get()

        :param offset: Offset from the start of the list from which to retrieve documents. 
        :type offset: int
        :param limit: Number of documents to return. 
        :type limit: int
        :param search: Search term. 
        :type search: str
        :param sort: Key on which to sort. 
        :type sort: str
        :param reverse: Sort order. 
        :type reverse: bool
        :param collections: Scopes the query by collection. 
        :type collections: list[str]
        :param account_ids: Scopes the query by account ID. 
        :type account_ids: list[str]
        :param fields: List of fields to retrieve. 
        :type fields: list[str]
        :param id: List of function IDs. 
        :type id: list[str]
        :param cloud_controller_addresses: List of cloud controller addresses which hold the functions. 
        :type cloud_controller_addresses: list[str]
        :param provider: Filters results by provider. 
        :type provider: list[str]
        :param region: Filters results by region. 
        :type region: list[str]
        :param runtime: Filters results by runtime. 
        :type runtime: list[str]
        :param version: Filters results by function version. 
        :type version: list[str]
        :param function_layers: Filters results by function layers. 
        :type function_layers: list[str]
        :param defended: Filters results by functions which are defended by a Defender and are connected to Console (true) or not (false). 
        :type defended: bool
        :param compliance_ids: Filters results by compliance ID. 
        :type compliance_ids: list[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: list[ServerlessFunctionInfo]
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_get_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_get_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_get  # noqa: E501

        ServerlessFunctions returns serverless functions   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param offset: Offset from the start of the list from which to retrieve documents. 
        :type offset: int
        :param limit: Number of documents to return. 
        :type limit: int
        :param search: Search term. 
        :type search: str
        :param sort: Key on which to sort. 
        :type sort: str
        :param reverse: Sort order. 
        :type reverse: bool
        :param collections: Scopes the query by collection. 
        :type collections: list[str]
        :param account_ids: Scopes the query by account ID. 
        :type account_ids: list[str]
        :param fields: List of fields to retrieve. 
        :type fields: list[str]
        :param id: List of function IDs. 
        :type id: list[str]
        :param cloud_controller_addresses: List of cloud controller addresses which hold the functions. 
        :type cloud_controller_addresses: list[str]
        :param provider: Filters results by provider. 
        :type provider: list[str]
        :param region: Filters results by region. 
        :type region: list[str]
        :param runtime: Filters results by runtime. 
        :type runtime: list[str]
        :param version: Filters results by function version. 
        :type version: list[str]
        :param function_layers: Filters results by function layers. 
        :type function_layers: list[str]
        :param defended: Filters results by functions which are defended by a Defender and are connected to Console (true) or not (false). 
        :type defended: bool
        :param compliance_ids: Filters results by compliance ID. 
        :type compliance_ids: list[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(list[ServerlessFunctionInfo], status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'offset',
            'limit',
            'search',
            'sort',
            'reverse',
            'collections',
            'account_ids',
            'fields',
            'id',
            'cloud_controller_addresses',
            'provider',
            'region',
            'runtime',
            'version',
            'function_layers',
            'defended',
            'compliance_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in local_var_params and local_var_params['offset'] is not None:  # noqa: E501
            query_params.append(('offset', local_var_params['offset']))  # noqa: E501
        if 'limit' in local_var_params and local_var_params['limit'] is not None:  # noqa: E501
            query_params.append(('limit', local_var_params['limit']))  # noqa: E501
        if 'search' in local_var_params and local_var_params['search'] is not None:  # noqa: E501
            query_params.append(('search', local_var_params['search']))  # noqa: E501
        if 'sort' in local_var_params and local_var_params['sort'] is not None:  # noqa: E501
            query_params.append(('sort', local_var_params['sort']))  # noqa: E501
        if 'reverse' in local_var_params and local_var_params['reverse'] is not None:  # noqa: E501
            query_params.append(('reverse', local_var_params['reverse']))  # noqa: E501
        if 'collections' in local_var_params and local_var_params['collections'] is not None:  # noqa: E501
            query_params.append(('collections', local_var_params['collections']))  # noqa: E501
            collection_formats['collections'] = 'multi'  # noqa: E501
        if 'account_ids' in local_var_params and local_var_params['account_ids'] is not None:  # noqa: E501
            query_params.append(('accountIDs', local_var_params['account_ids']))  # noqa: E501
            collection_formats['accountIDs'] = 'multi'  # noqa: E501
        if 'fields' in local_var_params and local_var_params['fields'] is not None:  # noqa: E501
            query_params.append(('fields', local_var_params['fields']))  # noqa: E501
            collection_formats['fields'] = 'multi'  # noqa: E501
        if 'id' in local_var_params and local_var_params['id'] is not None:  # noqa: E501
            query_params.append(('id', local_var_params['id']))  # noqa: E501
            collection_formats['id'] = 'multi'  # noqa: E501
        if 'cloud_controller_addresses' in local_var_params and local_var_params['cloud_controller_addresses'] is not None:  # noqa: E501
            query_params.append(('cloudControllerAddresses', local_var_params['cloud_controller_addresses']))  # noqa: E501
            collection_formats['cloudControllerAddresses'] = 'multi'  # noqa: E501
        if 'provider' in local_var_params and local_var_params['provider'] is not None:  # noqa: E501
            query_params.append(('provider', local_var_params['provider']))  # noqa: E501
            collection_formats['provider'] = 'multi'  # noqa: E501
        if 'region' in local_var_params and local_var_params['region'] is not None:  # noqa: E501
            query_params.append(('region', local_var_params['region']))  # noqa: E501
            collection_formats['region'] = 'multi'  # noqa: E501
        if 'runtime' in local_var_params and local_var_params['runtime'] is not None:  # noqa: E501
            query_params.append(('runtime', local_var_params['runtime']))  # noqa: E501
            collection_formats['runtime'] = 'multi'  # noqa: E501
        if 'version' in local_var_params and local_var_params['version'] is not None:  # noqa: E501
            query_params.append(('version', local_var_params['version']))  # noqa: E501
            collection_formats['version'] = 'multi'  # noqa: E501
        if 'function_layers' in local_var_params and local_var_params['function_layers'] is not None:  # noqa: E501
            query_params.append(('functionLayers', local_var_params['function_layers']))  # noqa: E501
            collection_formats['functionLayers'] = 'multi'  # noqa: E501
        if 'defended' in local_var_params and local_var_params['defended'] is not None:  # noqa: E501
            query_params.append(('defended', local_var_params['defended']))  # noqa: E501
        if 'compliance_ids' in local_var_params and local_var_params['compliance_ids'] is not None:  # noqa: E501
            query_params.append(('complianceIDs', local_var_params['compliance_ids']))  # noqa: E501
            collection_formats['complianceIDs'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {
            200: "list[ServerlessFunctionInfo]",
        }

        return self.api_client.call_api(
            '/api/v1/serverless', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def api_v1_serverless_names_get(self, **kwargs):  # noqa: E501
        """api_v1_serverless_names_get  # noqa: E501

        ServerlessFunctionNames returns serverless function names according to the query specification   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_names_get(async_req=True)
        >>> result = thread.get()

        :param offset: Offset from the start of the list from which to retrieve documents. 
        :type offset: int
        :param limit: Number of documents to return. 
        :type limit: int
        :param search: Search term. 
        :type search: str
        :param sort: Key on which to sort. 
        :type sort: str
        :param reverse: Sort order. 
        :type reverse: bool
        :param collections: Scopes the query by collection. 
        :type collections: list[str]
        :param account_ids: Scopes the query by account ID. 
        :type account_ids: list[str]
        :param fields: List of fields to retrieve. 
        :type fields: list[str]
        :param id: List of function IDs. 
        :type id: list[str]
        :param cloud_controller_addresses: List of cloud controller addresses which hold the functions. 
        :type cloud_controller_addresses: list[str]
        :param provider: Filters results by provider. 
        :type provider: list[str]
        :param region: Filters results by region. 
        :type region: list[str]
        :param runtime: Filters results by runtime. 
        :type runtime: list[str]
        :param version: Filters results by function version. 
        :type version: list[str]
        :param function_layers: Filters results by function layers. 
        :type function_layers: list[str]
        :param defended: Filters results by functions which are defended by a Defender and are connected to Console (true) or not (false). 
        :type defended: bool
        :param compliance_ids: Filters results by compliance ID. 
        :type compliance_ids: list[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: list[str]
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_names_get_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_names_get_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_names_get  # noqa: E501

        ServerlessFunctionNames returns serverless function names according to the query specification   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_names_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param offset: Offset from the start of the list from which to retrieve documents. 
        :type offset: int
        :param limit: Number of documents to return. 
        :type limit: int
        :param search: Search term. 
        :type search: str
        :param sort: Key on which to sort. 
        :type sort: str
        :param reverse: Sort order. 
        :type reverse: bool
        :param collections: Scopes the query by collection. 
        :type collections: list[str]
        :param account_ids: Scopes the query by account ID. 
        :type account_ids: list[str]
        :param fields: List of fields to retrieve. 
        :type fields: list[str]
        :param id: List of function IDs. 
        :type id: list[str]
        :param cloud_controller_addresses: List of cloud controller addresses which hold the functions. 
        :type cloud_controller_addresses: list[str]
        :param provider: Filters results by provider. 
        :type provider: list[str]
        :param region: Filters results by region. 
        :type region: list[str]
        :param runtime: Filters results by runtime. 
        :type runtime: list[str]
        :param version: Filters results by function version. 
        :type version: list[str]
        :param function_layers: Filters results by function layers. 
        :type function_layers: list[str]
        :param defended: Filters results by functions which are defended by a Defender and are connected to Console (true) or not (false). 
        :type defended: bool
        :param compliance_ids: Filters results by compliance ID. 
        :type compliance_ids: list[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(list[str], status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'offset',
            'limit',
            'search',
            'sort',
            'reverse',
            'collections',
            'account_ids',
            'fields',
            'id',
            'cloud_controller_addresses',
            'provider',
            'region',
            'runtime',
            'version',
            'function_layers',
            'defended',
            'compliance_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_names_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'offset' in local_var_params and local_var_params['offset'] is not None:  # noqa: E501
            query_params.append(('offset', local_var_params['offset']))  # noqa: E501
        if 'limit' in local_var_params and local_var_params['limit'] is not None:  # noqa: E501
            query_params.append(('limit', local_var_params['limit']))  # noqa: E501
        if 'search' in local_var_params and local_var_params['search'] is not None:  # noqa: E501
            query_params.append(('search', local_var_params['search']))  # noqa: E501
        if 'sort' in local_var_params and local_var_params['sort'] is not None:  # noqa: E501
            query_params.append(('sort', local_var_params['sort']))  # noqa: E501
        if 'reverse' in local_var_params and local_var_params['reverse'] is not None:  # noqa: E501
            query_params.append(('reverse', local_var_params['reverse']))  # noqa: E501
        if 'collections' in local_var_params and local_var_params['collections'] is not None:  # noqa: E501
            query_params.append(('collections', local_var_params['collections']))  # noqa: E501
            collection_formats['collections'] = 'multi'  # noqa: E501
        if 'account_ids' in local_var_params and local_var_params['account_ids'] is not None:  # noqa: E501
            query_params.append(('accountIDs', local_var_params['account_ids']))  # noqa: E501
            collection_formats['accountIDs'] = 'multi'  # noqa: E501
        if 'fields' in local_var_params and local_var_params['fields'] is not None:  # noqa: E501
            query_params.append(('fields', local_var_params['fields']))  # noqa: E501
            collection_formats['fields'] = 'multi'  # noqa: E501
        if 'id' in local_var_params and local_var_params['id'] is not None:  # noqa: E501
            query_params.append(('id', local_var_params['id']))  # noqa: E501
            collection_formats['id'] = 'multi'  # noqa: E501
        if 'cloud_controller_addresses' in local_var_params and local_var_params['cloud_controller_addresses'] is not None:  # noqa: E501
            query_params.append(('cloudControllerAddresses', local_var_params['cloud_controller_addresses']))  # noqa: E501
            collection_formats['cloudControllerAddresses'] = 'multi'  # noqa: E501
        if 'provider' in local_var_params and local_var_params['provider'] is not None:  # noqa: E501
            query_params.append(('provider', local_var_params['provider']))  # noqa: E501
            collection_formats['provider'] = 'multi'  # noqa: E501
        if 'region' in local_var_params and local_var_params['region'] is not None:  # noqa: E501
            query_params.append(('region', local_var_params['region']))  # noqa: E501
            collection_formats['region'] = 'multi'  # noqa: E501
        if 'runtime' in local_var_params and local_var_params['runtime'] is not None:  # noqa: E501
            query_params.append(('runtime', local_var_params['runtime']))  # noqa: E501
            collection_formats['runtime'] = 'multi'  # noqa: E501
        if 'version' in local_var_params and local_var_params['version'] is not None:  # noqa: E501
            query_params.append(('version', local_var_params['version']))  # noqa: E501
            collection_formats['version'] = 'multi'  # noqa: E501
        if 'function_layers' in local_var_params and local_var_params['function_layers'] is not None:  # noqa: E501
            query_params.append(('functionLayers', local_var_params['function_layers']))  # noqa: E501
            collection_formats['functionLayers'] = 'multi'  # noqa: E501
        if 'defended' in local_var_params and local_var_params['defended'] is not None:  # noqa: E501
            query_params.append(('defended', local_var_params['defended']))  # noqa: E501
        if 'compliance_ids' in local_var_params and local_var_params['compliance_ids'] is not None:  # noqa: E501
            query_params.append(('complianceIDs', local_var_params['compliance_ids']))  # noqa: E501
            collection_formats['complianceIDs'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {
            200: "list[str]",
        }

        return self.api_client.call_api(
            '/api/v1/serverless/names', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def api_v1_serverless_progress_get(self, **kwargs):  # noqa: E501
        """api_v1_serverless_progress_get  # noqa: E501

        ServerlessProgress returns the serverless scan progress   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_progress_get(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: list[SharedProgress]
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_progress_get_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_progress_get_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_progress_get  # noqa: E501

        ServerlessProgress returns the serverless scan progress   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_progress_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(list[SharedProgress], status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_progress_get" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {
            200: "list[SharedProgress]",
        }

        return self.api_client.call_api(
            '/api/v1/serverless/progress', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def api_v1_serverless_scan_post(self, **kwargs):  # noqa: E501
        """api_v1_serverless_scan_post  # noqa: E501

        ScanServerless starts a serverless scan   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_scan_post(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_scan_post_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_scan_post_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_scan_post  # noqa: E501

        ScanServerless starts a serverless scan   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_scan_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        local_var_params = locals()

        all_params = [
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_scan_post" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {}

        return self.api_client.call_api(
            '/api/v1/serverless/scan', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def api_v1_serverless_stop_post(self, **kwargs):  # noqa: E501
        """api_v1_serverless_stop_post  # noqa: E501

        StopServerlessScan stops the current serverless scan   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_stop_post(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        return self.api_v1_serverless_stop_post_with_http_info(**kwargs)  # noqa: E501

    def api_v1_serverless_stop_post_with_http_info(self, **kwargs):  # noqa: E501
        """api_v1_serverless_stop_post  # noqa: E501

        StopServerlessScan stops the current serverless scan   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_v1_serverless_stop_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        local_var_params = locals()

        all_params = [
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_serverless_stop_post" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501
        
        response_types_map = {}

        return self.api_client.call_api(
            '/api/v1/serverless/stop', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))
